name: Flutter Web Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: List Repository Contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "-----------------"
          echo "Search for pubspec.yaml:"
          find . -name "pubspec.yaml" -type f || echo "No pubspec.yaml found"
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
      
      - name: Initialize Flutter Project
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -type f | head -n 1 || echo "")
          
          if [ -n "$PUBSPEC_PATH" ]; then
            PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
            echo "Flutter project found at: $PROJECT_DIR"
            cd "$PROJECT_DIR"
            flutter pub get
          else
            echo "No pubspec.yaml found. Creating a new Flutter project..."
            flutter create my_flutter_web
            cd my_flutter_web
            flutter pub get
            
            # Eğer önceden yazılmış bir kodunuz varsa, buraya aktarabilirsiniz
            # örneğin, ../lib klasöründeki dosyaları kopyalayabilirsiniz
          fi
      
      - name: Build Web
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -type f | head -n 1 || echo "")
          
          if [ -n "$PUBSPEC_PATH" ]; then
            PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
            cd "$PROJECT_DIR"
          else
            cd my_flutter_web
          fi
          
          flutter build web --release
      
      - name: Create .nojekyll File
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -type f | head -n 1 || echo "")
          
          if [ -n "$PUBSPEC_PATH" ]; then
            PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
            touch "$PROJECT_DIR/build/web/.nojekyll"
          else
            touch my_flutter_web/build/web/.nojekyll
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my_flutter_web/build/web
          force_orphan: true
